import type { Clinic } from "./types";

export const clinics: Clinic[] = [
  {
    id: "1",
    name: "Main Hospital",
    status: "Active",
    statusColor: "text-[#16A34A]",
    statusBg: "bg-[#F0FDF4]",
    rating: 4.9,
    address: "123 Medical Center Drive, New York, NY 10001",
    phone: "+1 (555) 123-4567",
    email: "main@hospital.com",
    weekdayHours: "Mon-Fri: 7:00 AM - 9:00 PM",
    weekendHours: "Sat-Sun: 8:00 AM - 6:00 PM",
    staff: 48,
    providers: 12,
    patients: 1250,
    occupancy: 94,
    beds: 320,
    avgWaitTime: "12 min",
    headDoctor: "Dr. James Harrison",
    established: "1998",
    departments: ["Emergency", "Cardiology", "Neurology", "Orthopaedics", "Oncology", "Radiology"],
    services: [
      { label: "Emergency", color: "text-[#EF4444]", bg: "bg-[#FEF2F2]" },
      { label: "ICU Support", color: "text-[#7C3AED]", bg: "bg-[#FAF5FF]" },
      { label: "Surgery", color: "text-[#0284C7]", bg: "bg-[#EFF6FF]" },
      { label: "High Load", color: "text-[#EA580C]", bg: "bg-[#FFF7ED]" },
    ],
    accentFrom: "from-[#16A34A]",
    accentTo: "to-[#0284C7]",
  },
  {
    id: "2",
    name: "North Branch",
    status: "Active",
    statusColor: "text-[#0284C7]",
    statusBg: "bg-[#EFF6FF]",
    rating: 4.7,
    address: "456 North Avenue, Brooklyn, NY 11201",
    phone: "+1 (555) 234-5678",
    email: "north@hospital.com",
    weekdayHours: "Mon-Fri: 8:00 AM - 6:00 PM",
    weekendHours: "Sat: 9:00 AM - 1:00 PM",
    staff: 24,
    providers: 6,
    patients: 680,
    occupancy: 78,
    beds: 120,
    avgWaitTime: "18 min",
    headDoctor: "Dr. Sarah Mitchell",
    established: "2005",
    departments: ["General", "Pediatrics", "Dermatology", "Physiotherapy"],
    services: [
      { label: "General", color: "text-[#0284C7]", bg: "bg-[#EFF6FF]" },
      { label: "Pediatrics", color: "text-[#7C3AED]", bg: "bg-[#FAF5FF]" },
      { label: "Dermatology", color: "text-[#16A34A]", bg: "bg-[#F0FDF4]" },
    ],
    accentFrom: "from-[#0284C7]",
    accentTo: "to-[#7C3AED]",
  },
  {
    id: "3",
    name: "South Branch",
    status: "Active",
    statusColor: "text-[#16A34A]",
    statusBg: "bg-[#F0FDF4]",
    rating: 4.6,
    address: "789 South Boulevard, Queens, NY 11375",
    phone: "+1 (555) 345-6789",
    email: "south@hospital.com",
    weekdayHours: "Mon-Fri: 8:00 AM - 8:00 PM",
    weekendHours: "Sat-Sun: 9:00 AM - 4:00 PM",
    staff: 32,
    providers: 8,
    patients: 890,
    occupancy: 85,
    beds: 180,
    avgWaitTime: "15 min",
    headDoctor: "Dr. Robert Chen",
    established: "2010",
    departments: ["Cardiology", "Radiology", "Gastroenterology", "ENT", "Ophthalmology"],
    services: [
      { label: "Cardiology", color: "text-[#EF4444]", bg: "bg-[#FEF2F2]" },
      { label: "Radiology", color: "text-[#EA580C]", bg: "bg-[#FFF7ED]" },
      { label: "Equipped", color: "text-[#16A34A]", bg: "bg-[#F0FDF4]" },
    ],
    accentFrom: "from-[#EA580C]",
    accentTo: "to-[#EF4444]",
  },
  {
    id: "4",
    name: "Downtown Urgent Care",
    status: "Urgent Care",
    statusColor: "text-[#EF4444]",
    statusBg: "bg-[#FEF2F2]",
    rating: 4.6,
    address: "321 Downtown Plaza, Manhattan, NY 10003",
    phone: "+1 (555) 456-7890",
    email: "urgent@hospital.com",
    weekdayHours: "Open 24/7",
    weekendHours: "Open 24/7",
    staff: 20,
    providers: 5,
    patients: 430,
    occupancy: 62,
    beds: 45,
    avgWaitTime: "8 min",
    headDoctor: "Dr. Emily Watson",
    established: "2018",
    departments: ["Emergency", "Trauma", "First Aid"],
    services: [
      { label: "First Aid", color: "text-[#EF4444]", bg: "bg-[#FEF2F2]" },
      { label: "Walk-In", color: "text-[#F59E0B]", bg: "bg-[#FFFBEB]" },
      { label: "X-Ray", color: "text-[#0284C7]", bg: "bg-[#EFF6FF]" },
    ],
    accentFrom: "from-[#EF4444]",
    accentTo: "to-[#F59E0B]",
  },
];
