import { ActivityLog } from "./types";

export const CATEGORIES = ["All Activity", "Login", "Admin", "System", "Patient", "Appointment"] as const;

export const ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "1",
    user: "Dr. Sarah Wilson",
    role: "Doctor",
    avatar: "SW",
    action: "Patient Record Updated",
    description: "Updated medical history for patient James Cooper (ID: P-1042)",
    timestamp: "2 minutes ago",
    category: "patient",
    severity: "info",
  },
  {
    id: "2",
    user: "Admin System",
    role: "System",
    avatar: "SY",
    action: "Automatic Backup Completed",
    description: "Daily database backup completed successfully — 1.4 GB archived",
    timestamp: "15 minutes ago",
    category: "system",
    severity: "success",
  },
  {
    id: "3",
    user: "Dr. Michael Chen",
    role: "Doctor",
    avatar: "MC",
    action: "Login Successful",
    description: "Logged in from 192.168.1.45 — Chrome on Windows 11",
    timestamp: "32 minutes ago",
    category: "login",
    severity: "success",
  },
  {
    id: "4",
    user: "Nurse Emily Davis",
    role: "Nurse",
    avatar: "ED",
    action: "Appointment Rescheduled",
    description: "Moved appointment #A-2087 from 10:00 AM to 2:30 PM for patient Maria Lopez",
    timestamp: "1 hour ago",
    category: "appointment",
    severity: "info",
  },
  {
    id: "5",
    user: "Admin Portal",
    role: "System",
    avatar: "AP",
    action: "Failed Login Attempt",
    description: "3 failed login attempts for user admin@hospital.com — IP: 203.0.113.42",
    timestamp: "1 hour ago",
    category: "login",
    severity: "error",
  },
  {
    id: "6",
    user: "Dr. Rachel Green",
    role: "Doctor",
    avatar: "RG",
    action: "Prescription Created",
    description: "New prescription issued for patient Tom Harris — Amoxicillin 500mg",
    timestamp: "2 hours ago",
    category: "patient",
    severity: "info",
  },
  {
    id: "7",
    user: "John Miller",
    role: "Admin",
    avatar: "JM",
    action: "User Role Updated",
    description: "Changed role for nurse.kate@hospital.com from Nurse to Senior Nurse",
    timestamp: "2 hours ago",
    category: "admin",
    severity: "warning",
  },
  {
    id: "8",
    user: "System Monitor",
    role: "System",
    avatar: "SM",
    action: "Server Health Alert",
    description: "CPU usage exceeded 85% threshold on primary server for 5 minutes",
    timestamp: "3 hours ago",
    category: "system",
    severity: "warning",
  },
  {
    id: "9",
    user: "Dr. Sarah Wilson",
    role: "Doctor",
    avatar: "SW",
    action: "Appointment Completed",
    description: "Marked appointment #A-2083 as completed for patient Alex Turner",
    timestamp: "3 hours ago",
    category: "appointment",
    severity: "success",
  },
  {
    id: "10",
    user: "Lisa Thompson",
    role: "Receptionist",
    avatar: "LT",
    action: "New Patient Registered",
    description: "Registered new patient: David Brown (ID: P-1089) with NHS coverage",
    timestamp: "4 hours ago",
    category: "patient",
    severity: "success",
  },
  {
    id: "11",
    user: "John Miller",
    role: "Admin",
    avatar: "JM",
    action: "Billing Rule Modified",
    description: "Updated senior citizen discount from 10% to 15% effective immediately",
    timestamp: "4 hours ago",
    category: "admin",
    severity: "info",
  },
  {
    id: "12",
    user: "System",
    role: "System",
    avatar: "SY",
    action: "SSL Certificate Renewed",
    description: "SSL certificate auto-renewed for portal.hospital.com — valid until Mar 2027",
    timestamp: "5 hours ago",
    category: "system",
    severity: "success",
  },
];
