import type { AppointmentType } from "./types";

export const appointmentTypes: AppointmentType[] = [
  {
    id: "1",
    name: "General Checkup",
    description: "Routine health examination",
    duration: 30,
    mode: "Both",
    status: "Active",
    fee: 7,
    icon: "Stethoscope",
    color: "text-[#0284C7]",
    bg: "bg-[#EFF6FF]",
  },
  {
    id: "2",
    name: "Cardiology Consultation",
    description: "Heart and cardiovascular exam",
    duration: 45,
    mode: "In-Person",
    status: "Active",
    fee: 15,
    icon: "Heart",
    color: "text-[#EF4444]",
    bg: "bg-[#FEF2F2]",
  },
  {
    id: "3",
    name: "Telehealth Quick Consult",
    description: "Virtual consultation",
    duration: 25,
    mode: "Telehealth",
    status: "Active",
    fee: 4,
    icon: "Video",
    color: "text-[#16A34A]",
    bg: "bg-[#F0FDF4]",
  },
  {
    id: "4",
    name: "Follow-up Visit",
    description: "Post-treatment follow up",
    duration: 15,
    mode: "In-Person",
    status: "Active",
    fee: 5,
    icon: "ClipboardCheck",
    color: "text-[#7C3AED]",
    bg: "bg-[#FAF5FF]",
  },
  {
    id: "5",
    name: "Pediatric Checkup",
    description: "Children's health examination",
    duration: 35,
    mode: "In-Person",
    status: "Active",
    fee: 8,
    icon: "Baby",
    color: "text-[#EA580C]",
    bg: "bg-[#FFF7ED]",
  },
  {
    id: "6",
    name: "Mental Health Counsel",
    description: "Counseling session",
    duration: 60,
    mode: "Both",
    status: "Active",
    fee: 12,
    icon: "Brain",
    color: "text-[#0284C7]",
    bg: "bg-[#EFF6FF]",
  },
  {
    id: "7",
    name: "Vaccination",
    description: "Immunization service",
    duration: 20,
    mode: "In-Person",
    status: "Active",
    fee: 3,
    icon: "Syringe",
    color: "text-[#16A34A]",
    bg: "bg-[#F0FDF4]",
  },
  {
    id: "8",
    name: "Lab Results Review",
    description: "Lab discussion",
    duration: 30,
    mode: "Both",
    status: "Inactive",
    fee: 4,
    icon: "FlaskConical",
    color: "text-[#7C3AED]",
    bg: "bg-[#FAF5FF]",
  },
  {
    id: "9",
    name: "Orthopedic Assessment",
    description: "Bone and joint evaluation",
    duration: 40,
    mode: "In-Person",
    status: "Active",
    fee: 14,
    icon: "Bone",
    color: "text-[#EA580C]",
    bg: "bg-[#FFF7ED]",
  },
  {
    id: "10",
    name: "Eye Examination",
    description: "Vision and eye health check",
    duration: 30,
    mode: "In-Person",
    status: "Active",
    fee: 10,
    icon: "Eye",
    color: "text-[#0284C7]",
    bg: "bg-[#EFF6FF]",
  },
  {
    id: "11",
    name: "Dermatology Consult",
    description: "Skin condition assessment",
    duration: 25,
    mode: "Telehealth",
    status: "Active",
    fee: 9,
    icon: "Microscope",
    color: "text-[#EF4444]",
    bg: "bg-[#FEF2F2]",
  },
  {
    id: "12",
    name: "Prescription Renewal",
    description: "Medication review and renewal",
    duration: 15,
    mode: "Telehealth",
    status: "Active",
    fee: 5,
    icon: "Pill",
    color: "text-[#16A34A]",
    bg: "bg-[#F0FDF4]",
  },
  {
    id: "13",
    name: "Urgent Care Visit",
    description: "Non-emergency urgent assessment",
    duration: 45,
    mode: "In-Person",
    status: "Inactive",
    fee: 18,
    icon: "Thermometer",
    color: "text-[#EF4444]",
    bg: "bg-[#FEF2F2]",
  },
];

export const MODES = ["In-Person", "Telehealth", "Both"] as const;
export const STATUSES = ["Active", "Inactive"] as const;
export const DURATIONS = ["15", "20", "25", "30", "35", "40", "45", "60"] as const;
