import { WaitingPatient } from "./types";

export const WAITING_PATIENTS: WaitingPatient[] = [
  {
    id: "WP-001",
    name: "Amelia Rodriguez",
    avatar: "AR",
    type: "Follow-up Consultation",
    waitingTime: "12 mins",
    waitingMins: 12,
    status: "Ready",
    hasDocs: true,
    hasForm: true,
  },
  {
    id: "WP-002",
    name: "Benjamin Carter",
    avatar: "BC",
    type: "Prescription Refill",
    waitingTime: "8 mins",
    waitingMins: 8,
    status: "Joining Soon",
    hasDocs: true,
    hasForm: true,
  },
  {
    id: "WP-003",
    name: "Chloe Davis",
    avatar: "CD",
    type: "General Check-up",
    waitingTime: "2 mins",
    waitingMins: 2,
    status: "Waiting",
    hasDocs: false,
    hasForm: true,
  },
  {
    id: "WP-004",
    name: "Daniel Foster",
    avatar: "DF",
    type: "Lab Results Review",
    waitingTime: "1 min",
    waitingMins: 1,
    status: "Waiting",
    hasDocs: true,
    hasForm: false,
  },
  {
    id: "WP-005",
    name: "Eleanor Grant",
    avatar: "EG",
    type: "Mental Health Check-in",
    waitingTime: "5 mins",
    waitingMins: 5,
    status: "Ready",
    hasDocs: false,
    hasForm: true,
  },
];
