import type { Patient } from "./types";

export const patients: Patient[] = [
  {
    id: "1",
    name: "Sarah Anderson",
    age: 34,
    gender: "Female",
    avatar: "SA",
    color: "bg-[#0284C7]",
    status: "Active",
    patientId: "PT-2847",
    phone: "+1 (555) 123-4567",
    email: "sarah.anderson@email.com",
    address: "742 Evergreen Terrace",
    insurance: "Blue Cross",
    primaryDoctor: "Dr. James Wilson",
    lastVisit: "3 days ago",
    nextAppointment: "Dec 14, 2025",
    balanceDue: "£ 850",
    conditions: ["Hypertension", "Type 2 Diabetes"],
  },
  {
    id: "2",
    name: "Michael Chen",
    age: 42,
    gender: "Male",
    avatar: "MC",
    color: "bg-[#7C3AED]",
    status: "Active",
    patientId: "PT-2848",
    phone: "+1 (555) 234-5678",
    email: "michael.chen@email.com",
    address: "113 Oak Street, Boston",
    insurance: "Aetna",
    primaryDoctor: "Dr. Sarah Johnson",
    lastVisit: "5 days ago",
    nextAppointment: "Dec 20, 2025",
    balanceDue: "£ 90.0",
    conditions: ["Asthma"],
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    age: 29,
    gender: "Female",
    avatar: "ER",
    color: "bg-[#16A34A]",
    status: "Active",
    patientId: "PT-2849",
    phone: "+1 (555) 345-6789",
    email: "emily.rodriguez@email.com",
    address: "456 Maple Ave, Los Angeles",
    insurance: "United Health",
    primaryDoctor: "Dr. Michael Brown",
    lastVisit: "1 week ago",
    nextAppointment: "Not scheduled",
    balanceDue: "£ 0",
    conditions: [],
  },
  {
    id: "4",
    name: "James Thompson",
    age: 56,
    gender: "Male",
    avatar: "JT",
    color: "bg-[#EA580C]",
    status: "Critical",
    patientId: "PT-2850",
    phone: "+1 (555) 456-7890",
    email: "james.thompson@email.com",
    address: "89 Park Lane, Chicago",
    insurance: "Medicare",
    primaryDoctor: "Dr. Lisa Anderson",
    lastVisit: "Yesterday",
    nextAppointment: "Dec 10, 2025",
    balanceDue: "£ 2,400",
    conditions: ["Heart Disease", "Diabetes", "Hypertension"],
  },
  {
    id: "5",
    name: "Olivia Patel",
    age: 38,
    gender: "Female",
    avatar: "OP",
    color: "bg-[#EF4444]",
    status: "Active",
    patientId: "PT-2851",
    phone: "+1 (555) 567-8901",
    email: "olivia.patel@email.com",
    address: "321 Elm St, Houston",
    insurance: "Cigna",
    primaryDoctor: "Dr. Robert Martinez",
    lastVisit: "2 weeks ago",
    nextAppointment: "Dec 18, 2025",
    balanceDue: "£ 150",
    conditions: ["Migraine"],
  },
  {
    id: "6",
    name: "David Kim",
    age: 61,
    gender: "Male",
    avatar: "DK",
    color: "bg-[#F59E0B]",
    status: "Active",
    patientId: "PT-2852",
    phone: "+1 (555) 678-9012",
    email: "david.kim@email.com",
    address: "567 Broadway, New York",
    insurance: "Humana",
    primaryDoctor: "Dr. Emily Chen",
    lastVisit: "10 days ago",
    nextAppointment: "Dec 22, 2025",
    balanceDue: "£ 320",
    conditions: ["Arthritis", "High Cholesterol"],
  },
  {
    id: "7",
    name: "Sophia Williams",
    age: 25,
    gender: "Female",
    avatar: "SW",
    color: "bg-[#0284C7]",
    status: "Inactive",
    patientId: "PT-2853",
    phone: "+1 (555) 789-0123",
    email: "sophia.williams@email.com",
    address: "234 Pine Rd, Seattle",
    insurance: "Kaiser",
    primaryDoctor: "Dr. James Wilson",
    lastVisit: "3 months ago",
    nextAppointment: "Not scheduled",
    balanceDue: "£ 0",
    conditions: [],
  },
  {
    id: "8",
    name: "Robert Johnson",
    age: 48,
    gender: "Male",
    avatar: "RJ",
    color: "bg-[#7C3AED]",
    status: "Active",
    patientId: "PT-2854",
    phone: "+1 (555) 890-1234",
    email: "robert.johnson@email.com",
    address: "890 Cedar Blvd, Miami",
    insurance: "Blue Shield",
    primaryDoctor: "Dr. Sarah Johnson",
    lastVisit: "4 days ago",
    nextAppointment: "Dec 16, 2025",
    balanceDue: "£ 1,100",
    conditions: ["Back Pain", "Sleep Apnea"],
  },
];

export const STATUSES = ["Active", "Inactive", "Critical"];
