// import { Appointment } from "./types";

// export const STATUS_TABS = ["All", "Scheduled", "In Progress", "Completed", "Cancelled", "No Show"] as const;

// export const APPOINTMENTS: Appointment[] = [
//   {
//     id: "APT-001",
//     patientName: "James T. Wilson",
//     patientId: "PT-B439201",
//     avatar: "JW",
//     age: 34,
//     gender: "Male",
//     type: "Follow-up Consultation",
//     date: "2025-12-10",
//     time: "09:00 AM",
//     status: "In Progress",
//     mode: "Telehealth",
//     reason: "Diabetes follow-up, review A1C levels",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-002",
//     patientName: "Emma R. Davis",
//     patientId: "PT-C782105",
//     avatar: "ED",
//     age: 28,
//     gender: "Female",
//     type: "Initial Consultation",
//     date: "2025-12-10",
//     time: "09:30 AM",
//     status: "Scheduled",
//     mode: "In-Clinic",
//     reason: "Chronic migraine evaluation",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-003",
//     patientName: "Robert A. Chen",
//     patientId: "PT-A195840",
//     avatar: "RC",
//     age: 52,
//     gender: "Male",
//     type: "Cardiology Follow-up",
//     date: "2025-12-10",
//     time: "10:00 AM",
//     status: "Scheduled",
//     mode: "In-Clinic",
//     reason: "Post-MI check, medication review",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-004",
//     patientName: "Maria Lopez",
//     patientId: "PT-D654321",
//     avatar: "ML",
//     age: 45,
//     gender: "Female",
//     type: "Routine Check-up",
//     date: "2025-12-10",
//     time: "10:30 AM",
//     status: "Scheduled",
//     mode: "Telehealth",
//     reason: "Annual wellness visit, blood work review",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-005",
//     patientName: "David Kim",
//     patientId: "PT-E987654",
//     avatar: "DK",
//     age: 61,
//     gender: "Male",
//     type: "Specialist Referral",
//     date: "2025-12-10",
//     time: "11:00 AM",
//     status: "Completed",
//     mode: "In-Clinic",
//     reason: "Pulmonology referral, chronic cough",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-006",
//     patientName: "Sarah Thompson",
//     patientId: "PT-F112233",
//     avatar: "ST",
//     age: 37,
//     gender: "Female",
//     type: "Follow-up Consultation",
//     date: "2025-12-10",
//     time: "11:30 AM",
//     status: "Cancelled",
//     mode: "Telehealth",
//     reason: "Post-surgery follow-up — patient rescheduled",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-007",
//     patientName: "Alex Turner",
//     patientId: "PT-G445566",
//     avatar: "AT",
//     age: 29,
//     gender: "Male",
//     type: "Urgent Care",
//     date: "2025-12-10",
//     time: "01:00 PM",
//     status: "Scheduled",
//     mode: "In-Clinic",
//     reason: "Acute lower back pain, possible disc issue",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-008",
//     patientName: "Linda Martinez",
//     patientId: "PT-H778899",
//     avatar: "LM",
//     age: 55,
//     gender: "Female",
//     type: "Lab Review",
//     date: "2025-12-10",
//     time: "01:30 PM",
//     status: "No Show",
//     mode: "Telehealth",
//     reason: "Review blood panel results",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-009",
//     patientName: "Tom Harris",
//     patientId: "PT-I334455",
//     avatar: "TH",
//     age: 42,
//     gender: "Male",
//     type: "Prescription Renewal",
//     date: "2025-12-09",
//     time: "02:00 PM",
//     status: "Completed",
//     mode: "Telehealth",
//     reason: "Renew Metformin and Lisinopril prescriptions",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-010",
//     patientName: "Rachel Green",
//     patientId: "PT-J667788",
//     avatar: "RG",
//     age: 31,
//     gender: "Female",
//     type: "Mental Health",
//     date: "2025-12-09",
//     time: "03:00 PM",
//     status: "Completed",
//     mode: "Telehealth",
//     reason: "Anxiety management, medication adjustment",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-011",
//     patientName: "George Patel",
//     patientId: "PT-K990011",
//     avatar: "GP",
//     age: 67,
//     gender: "Male",
//     type: "Cardiology Follow-up",
//     date: "2025-12-09",
//     time: "04:00 PM",
//     status: "Completed",
//     mode: "In-Clinic",
//     reason: "ECG review, blood pressure monitoring",
//     doctor: "Dr. Sarah Wilson",
//   },
//   {
//     id: "APT-012",
//     patientName: "Nina Brooks",
//     patientId: "PT-L223344",
//     avatar: "NB",
//     age: 24,
//     gender: "Female",
//     type: "Initial Consultation",
//     date: "2025-12-11",
//     time: "09:00 AM",
//     status: "Scheduled",
//     mode: "In-Clinic",
//     reason: "New patient intake, general assessment",
//     doctor: "Dr. Sarah Wilson",
//   },
// ];
