import { PatientAppointment } from "./types";

export const appointments: PatientAppointment[] = [
  {
    id: "APT-001",
    doctor: {
      name: "Dr. James Wilson",
      specialty: "Cardiologist",
      initials: "JW",
      color: "#0284C7",
      hospital: "St. Mary's Hospital",
    },
    date: "2026-03-12",
    time: "09:30 AM",
    status: "Confirmed",
    mode: "Video Call",
    reason: "Routine Checkup",
  },
  {
    id: "APT-002",
    doctor: {
      name: "Dr. Sarah Smith",
      specialty: "Dermatologist",
      initials: "SS",
      color: "#7C3AED",
      hospital: "Royal London Hospital",
    },
    date: "2026-03-15",
    time: "11:00 AM",
    status: "Pending",
    mode: "In-Person",
    reason: "Skin Allergy Follow-up",
  },
  {
    id: "APT-003",
    doctor: {
      name: "Dr. Mark Chan",
      specialty: "General Physician",
      initials: "MC",
      color: "#059669",
      hospital: "City Health Clinic",
    },
    date: "2026-03-18",
    time: "02:00 PM",
    status: "Confirmed",
    mode: "In-Person",
    reason: "Annual Physical Exam",
  },
  {
    id: "APT-004",
    doctor: {
      name: "Dr. Emily Carter",
      specialty: "Neurologist",
      initials: "EC",
      color: "#EA580C",
      hospital: "King's College Hospital",
    },
    date: "2026-03-05",
    time: "10:15 AM",
    status: "Completed",
    mode: "Video Call",
    reason: "Migraine Consultation",
  },
  {
    id: "APT-005",
    doctor: {
      name: "Dr. Robert Hayes",
      specialty: "Orthopaedic Surgeon",
      initials: "RH",
      color: "#0891B2",
      hospital: "St. Mary's Hospital",
    },
    date: "2026-02-28",
    time: "03:30 PM",
    status: "Completed",
    mode: "In-Person",
    reason: "Knee Pain Assessment",
  },
  {
    id: "APT-006",
    doctor: {
      name: "Dr. Lisa Park",
      specialty: "Psychiatrist",
      initials: "LP",
      color: "#D946EF",
      hospital: "Maudsley Hospital",
    },
    date: "2026-02-20",
    time: "09:00 AM",
    status: "Cancelled",
    mode: "Video Call",
    reason: "Therapy Session",
  },
  {
    id: "APT-007",
    doctor: {
      name: "Dr. Ahmed Khan",
      specialty: "ENT Specialist",
      initials: "AK",
      color: "#CA8A04",
      hospital: "Royal London Hospital",
    },
    date: "2026-02-14",
    time: "04:00 PM",
    status: "Completed",
    mode: "In-Person",
    reason: "Sinus Infection",
  },
  {
    id: "APT-008",
    doctor: {
      name: "Dr. James Wilson",
      specialty: "Cardiologist",
      initials: "JW",
      color: "#0284C7",
      hospital: "St. Mary's Hospital",
    },
    date: "2026-02-10",
    time: "11:30 AM",
    status: "No Show",
    mode: "Video Call",
    reason: "Heart Monitoring Review",
  },
];

export const STATUS_OPTIONS = ["All", "Confirmed", "Pending", "Completed", "Cancelled", "No Show"] as const;
