import type { Provider } from "./types";

export const providers: Provider[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    department: "Cardiology",
    location: "Main Hospital - South Branch",
    status: "Active",
    rating: 4.8,
    patients: 245,
    nextAvailable: "Today, 2:15 PM",
    avatar: "SJ",
    color: "bg-[#0284C7]",
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    specialty: "Neurology",
    department: "Neurology",
    location: "Main Hospital",
    status: "Active",
    rating: 4.9,
    patients: 198,
    nextAvailable: "Today, 3:00 PM",
    avatar: "MC",
    color: "bg-[#16A34A]",
  },
  {
    id: "3",
    name: "Dr. Emily Roberts",
    specialty: "Pediatrics",
    department: "Pediatrics",
    location: "South Branch - Care Hospital",
    status: "Active",
    rating: 4.7,
    patients: 200,
    nextAvailable: "Today, 4:30 PM",
    avatar: "ER",
    color: "bg-[#EA580C]",
  },
  {
    id: "4",
    name: "Dr. James Williams",
    specialty: "Orthopedic Surgeon",
    department: "Orthopedics",
    location: "Main Hospital",
    status: "Active",
    rating: 4.6,
    patients: 45,
    nextAvailable: "Jan 15, 10:30 AM",
    avatar: "JW",
    color: "bg-[#7C3AED]",
  },
  {
    id: "5",
    name: "Dr. Lisa Anderson",
    specialty: "Dermatology",
    department: "Dermatology",
    location: "East Side Clinic",
    status: "Active",
    rating: 4.5,
    patients: 127,
    nextAvailable: "Dec 20, 11:00 AM",
    avatar: "LA",
    color: "bg-[#EF4444]",
  },
  {
    id: "6",
    name: "Dr. Robert Mitchell",
    specialty: "Internal Medicine",
    department: "General Medicine",
    location: "Main Hospital - South Branch",
    status: "Active",
    rating: 4.4,
    patients: 310,
    nextAvailable: "Today, 1:00 PM",
    avatar: "RM",
    color: "bg-[#0284C7]",
  },
  {
    id: "7",
    name: "Dr. Amanda Foster",
    specialty: "Psychiatry",
    department: "Mental Health",
    location: "Main Hospital",
    status: "Active",
    rating: 4.8,
    patients: 89,
    nextAvailable: "Today, 2:30 PM",
    avatar: "AF",
    color: "bg-[#EA580C]",
  },
  {
    id: "8",
    name: "Dr. David Kumar",
    specialty: "Nephrology",
    department: "Nephrology",
    location: "North Campus Hospital",
    status: "On Leave",
    rating: 4.3,
    patients: 76,
    nextAvailable: "N/A",
    avatar: "DK",
    color: "bg-[#16A34A]",
  },
  {
    id: "9",
    name: "Dr. Patricia Lee",
    specialty: "Oncology",
    department: "Oncology",
    location: "Main Hospital",
    status: "Active",
    rating: 4.9,
    patients: 156,
    nextAvailable: "Tomorrow, 9:00 AM",
    avatar: "PL",
    color: "bg-[#7C3AED]",
  },
  {
    id: "10",
    name: "Dr. Thomas Moore",
    specialty: "Pulmonology",
    department: "Pulmonology",
    location: "South Branch",
    status: "Active",
    rating: 4.6,
    patients: 112,
    nextAvailable: "Today, 5:00 PM",
    avatar: "TM",
    color: "bg-[#EF4444]",
  },
  {
    id: "11",
    name: "Dr. Nancy Clark",
    specialty: "Endocrinology",
    department: "Endocrinology",
    location: "East Side Clinic",
    status: "Inactive",
    rating: 4.2,
    patients: 64,
    nextAvailable: "N/A",
    avatar: "NC",
    color: "bg-[#0284C7]",
  },
  {
    id: "12",
    name: "Dr. Kevin Harris",
    specialty: "Radiology",
    department: "Radiology",
    location: "Main Hospital",
    status: "Active",
    rating: 4.7,
    patients: 203,
    nextAvailable: "Today, 11:30 AM",
    avatar: "KH",
    color: "bg-[#EA580C]",
  },
];

export const DEPARTMENTS = [
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Dermatology",
  "General Medicine",
  "Mental Health",
  "Nephrology",
  "Oncology",
  "Pulmonology",
  "Endocrinology",
  "Radiology",
] as const;

export const SPECIALTIES = [
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedic Surgeon",
  "Dermatology",
  "Internal Medicine",
  "Psychiatry",
  "Nephrology",
  "Oncology",
  "Pulmonology",
  "Endocrinology",
  "Radiology",
] as const;

export const STATUSES = ["Active", "On Leave", "Inactive"] as const;

export const LOCATIONS = [
  "Main Hospital",
  "Main Hospital - South Branch",
  "South Branch - Care Hospital",
  "East Side Clinic",
  "North Campus Hospital",
  "South Branch",
] as const;
