import type { User } from "./types";

export const users: User[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@hospital.com",
    role: "Doctor",
    department: "Cardiology",
    status: "Active",
    lastLogin: "2 hours ago",
    avatar: "SJ",
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    email: "michael.chen@hospital.com",
    role: "Doctor",
    department: "Neurology",
    status: "Active",
    lastLogin: "5 hours ago",
    avatar: "MC",
  },
  {
    id: "3",
    name: "Emily Martinez",
    email: "emily.martinez@hospital.com",
    role: "Nurse",
    department: "Emergency",
    status: "Active",
    lastLogin: "1 hour ago",
    avatar: "EM",
  },
  {
    id: "4",
    name: "James Wilson",
    email: "james.wilson@hospital.com",
    role: "Admin",
    department: "Administration",
    status: "Active",
    lastLogin: "30 mins ago",
    avatar: "JW",
  },
  {
    id: "5",
    name: "Dr. Lisa Anderson",
    email: "lisa.anderson@hospital.com",
    role: "Doctor",
    department: "Pediatrics",
    status: "Inactive",
    lastLogin: "3 days ago",
    avatar: "LA",
  },
  {
    id: "6",
    name: "Robert Taylor",
    email: "robert.taylor@hospital.com",
    role: "Staff",
    department: "Laboratory",
    status: "Active",
    lastLogin: "4 hours ago",
    avatar: "RT",
  },
  {
    id: "7",
    name: "Dr. Amanda White",
    email: "amanda.white@hospital.com",
    role: "Doctor",
    department: "Orthopedics",
    status: "Active",
    lastLogin: "1 day ago",
    avatar: "AW",
  },
  {
    id: "8",
    name: "Daniel Brown",
    email: "daniel.brown@hospital.com",
    role: "Nurse",
    department: "ICU",
    status: "Pending",
    lastLogin: "Never",
    avatar: "DB",
  },
  {
    id: "9",
    name: "Dr. Patricia Lee",
    email: "patricia.lee@hospital.com",
    role: "Doctor",
    department: "Dermatology",
    status: "Active",
    lastLogin: "6 hours ago",
    avatar: "PL",
  },
  {
    id: "10",
    name: "Kevin Harris",
    email: "kevin.harris@hospital.com",
    role: "Staff",
    department: "Radiology",
    status: "Active",
    lastLogin: "2 days ago",
    avatar: "KH",
  },
  {
    id: "11",
    name: "Dr. Nancy Clark",
    email: "nancy.clark@hospital.com",
    role: "Doctor",
    department: "Oncology",
    status: "Active",
    lastLogin: "3 hours ago",
    avatar: "NC",
  },
  {
    id: "12",
    name: "Sophie Turner",
    email: "sophie.turner@hospital.com",
    role: "Nurse",
    department: "Cardiology",
    status: "Active",
    lastLogin: "1 hour ago",
    avatar: "ST",
  },
  {
    id: "13",
    name: "Dr. William Davis",
    email: "william.davis@hospital.com",
    role: "Doctor",
    department: "Surgery",
    status: "Inactive",
    lastLogin: "1 week ago",
    avatar: "WD",
  },
  {
    id: "14",
    name: "Maria Garcia",
    email: "maria.garcia@hospital.com",
    role: "Admin",
    department: "Administration",
    status: "Active",
    lastLogin: "5 hours ago",
    avatar: "MG",
  },
  {
    id: "15",
    name: "Dr. Thomas Moore",
    email: "thomas.moore@hospital.com",
    role: "Doctor",
    department: "Neurology",
    status: "Active",
    lastLogin: "8 hours ago",
    avatar: "TM",
  },
  {
    id: "16",
    name: "Jessica Wright",
    email: "jessica.wright@hospital.com",
    role: "Nurse",
    department: "Emergency",
    status: "Active",
    lastLogin: "45 mins ago",
    avatar: "JR",
  },
];

export const ROLES = ["Doctor", "Nurse", "Admin", "Staff"] as const;
export const STATUSES = ["Active", "Inactive", "Pending"] as const;
export const DEPARTMENTS = [
  "Cardiology",
  "Neurology",
  "Emergency",
  "Administration",
  "Pediatrics",
  "Laboratory",
  "Orthopedics",
  "ICU",
  "Dermatology",
  "Radiology",
  "Oncology",
  "Surgery",
] as const;
