export const providerDetail = {
  id: "1",
  firstName: "Sarah",
  lastName: "Johnson",
  fullName: "Dr. Sarah Johnson",
  dateOfBirth: "March 15, 1985",
  gender: "Female",
  age: 38,
  employeeId: "EMP-12345",
  email: "sarah.johnson@hospital.com",
  phone: "+1 (555) 123-4567",
  emergencyContact: "+1 (555) 987-6543",
  address: "123 Medical Plaza, Suite 450\nNew York, NY 10001",
  specialty: "Cardiologist",
  department: "Cardiology",
  yearsOfExperience: 12,
  joinDate: "January 15, 2018",
  employmentStatus: "Full-Time",
  bio: "Dr. Sarah Johnson is a board-certified cardiologist with over 12 years of experience in cardiovascular medicine. She specializes in interventional cardiology and has performed over 500 successful procedures. Dr. Johnson is passionate about patient care and education.",
  specializations: ["Interventional Cardiology", "Echocardiography", "Heart Failure"],
  avatar: "SJ",
  color: "bg-[#0284C7]",
  schedule: {
    totalHoursWeek: 38,
    workingDays: 5,
    avgPatientsDay: 11,
    days: [
      { day: "Monday", from: "09:00", to: "17:00", patients: 12, active: true },
      { day: "Tuesday", from: "09:00", to: "17:00", patients: 10, active: true },
      { day: "Wednesday", from: "09:00", to: "17:00", patients: 14, active: true },
      { day: "Thursday", from: "09:00", to: "17:00", patients: 11, active: true },
      { day: "Friday", from: "09:00", to: "15:00", patients: 8, active: true },
      { day: "Saturday", from: "", to: "", patients: 0, active: false },
      { day: "Sunday", from: "", to: "", patients: 0, active: false },
    ],
    lunchBreak: "12:00 PM - 1:00 PM",
    bufferTime: "15 min between appointments",
  },
  locations: [
    {
      id: "1",
      name: "Main Hospital",
      primary: true,
      room: "Cardiology Wing, Room 301",
      address: "123 Medical Center Dr, New York, NY 10001",
      workingDays: ["Monday", "Tuesday", "Wednesday"],
    },
    {
      id: "2",
      name: "North Branch",
      primary: false,
      room: "Suite 205",
      address: "456 North Ave, New York, NY 10002",
      workingDays: ["Thursday", "Friday"],
    },
  ],
  appointmentRules: {
    duration: "30 minutes",
    buffer: "15 minutes",
    maxDaily: "16 appointments",
    advanceWindow: "30 days",
    sameDayBooking: true,
    onlineBooking: true,
    autoConfirmation: true,
    cancellationWindow: "24 hours",
    noShowFee: "£50",
  },
  telehealth: {
    enabled: true,
    platform: "Zoom Healthcare",
    maxDailyVirtual: 10,
    avgSessionDuration: "25 minutes",
    totalVirtualVisits: 48,
    thisMonth: 48,
    satisfaction: 4.8,
    noShowRate: "2.1%",
    features: ["HD Video", "Screen Share", "Recording"],
  },
  certifications: [
    {
      id: "1",
      name: "Board Certification in Cardiology",
      issuer: "American Board of Internal Medicine",
      issued: "June 2015",
      expires: "June 2025",
      status: "Active",
    },
    {
      id: "2",
      name: "Advanced Cardiac Life Support (ACLS)",
      issuer: "American Heart Association",
      issued: "January 2023",
      expires: "January 2025",
      status: "Active",
    },
    {
      id: "3",
      name: "Interventional Cardiology Fellowship",
      issuer: "Johns Hopkins Hospital",
      issued: "July 2014",
      expires: null,
      status: "Active",
    },
  ],
  medicalLicense: {
    number: "MD-NY-123456789",
    status: "Active & Verified",
    expiry: "December 31, 2025",
  },
  deaCertificate: {
    number: "BJ1234567",
    status: "Valid",
    expiry: "March 15, 2026",
  },
  documents: [
    { name: "Medical License.pdf", size: "2.4 MB", date: "Jan 15, 2024", tag: "License", tagColor: "text-[#EF4444] bg-[#FEF2F2]" },
    { name: "Board Certification.pdf", size: "1.8 MB", date: "Jan 15, 2024", tag: "Certificate", tagColor: "text-[#0284C7] bg-[#EFF6FF]" },
    { name: "DEA Certificate.pdf", size: "1.2 MB", date: "Jan 15, 2024", tag: "Certificate", tagColor: "text-[#0284C7] bg-[#EFF6FF]" },
    { name: "Insurance Policy.pdf", size: "3.1 MB", date: "Jan 10, 2024", tag: "Insurance", tagColor: "text-[#16A34A] bg-[#F0FDF4]" },
    { name: "Resume CV.pdf", size: "890 KB", date: "Dec 20, 2023", tag: "Resume", tagColor: "text-[#7C3AED] bg-[#FAF5FF]" },
    { name: "Background Check.pdf", size: "450 KB", date: "Dec 15, 2023", tag: "Verification", tagColor: "text-[#EA580C] bg-[#FFF7ED]" },
  ],
  assistants: [
    {
      id: "1",
      name: "Emily Carter",
      role: "Medical Assistant",
      status: "Active",
      email: "emily.carter@hospital.com",
      phone: "+1 (555) 234-5678",
      avatar: "EC",
      color: "bg-[#EF4444]",
    },
    {
      id: "2",
      name: "Michael Torres",
      role: "Nurse Practitioner",
      status: "Active",
      email: "michael.torres@hospital.com",
      phone: "+1 (555) 345-6789",
      avatar: "MT",
      color: "bg-[#0284C7]",
    },
  ],
};
