import type { NotificationTemplate, NotificationCategory } from "./types";

export const CATEGORIES: { label: string; value: NotificationCategory | "All" }[] = [
  { label: "All Templates", value: "All" },
  { label: "Appointment", value: "Appointment" },
  { label: "Patient", value: "Patient" },
  { label: "Billing", value: "Billing" },
  { label: "System", value: "System" },
];

export const templates: NotificationTemplate[] = [
  {
    id: "1",
    name: "Appointment Confirmation",
    description: "Sent to patients when an appointment is confirmed by the clinic or auto-confirmed after booking.",
    category: "Appointment",
    channels: ["SMS", "Email"],
    variables: ["{patient_name}", "{date}", "{time}", "{doctor_name}", "{location}"],
    color: "text-[#EA580C]",
    bgColor: "bg-[#FFF7ED]",
  },
  {
    id: "2",
    name: "Appointment Reminder",
    description: "Automated reminder sent to patients before their scheduled appointment to reduce no-shows.",
    category: "Appointment",
    channels: ["SMS", "Push"],
    variables: ["{patient_name}", "{date}", "{time}", "{doctor_name}"],
    color: "text-[#7C3AED]",
    bgColor: "bg-[#FAF5FF]",
  },
  {
    id: "3",
    name: "Appointment Cancellation",
    description: "Notification sent when an appointment is cancelled by either the patient or the provider.",
    category: "Appointment",
    channels: ["Email"],
    variables: ["{patient_name}", "{date}", "{doctor_name}", "{reason}"],
    color: "text-[#EF4444]",
    bgColor: "bg-[#FEF2F2]",
  },
  {
    id: "4",
    name: "New Patient Welcome",
    description: "Welcome message sent to newly registered patients with portal access and next steps.",
    category: "Patient",
    channels: ["Email", "SMS"],
    variables: ["{patient_name}", "{portal_link}", "{clinic_name}"],
    color: "text-[#0284C7]",
    bgColor: "bg-[#EFF6FF]",
  },
  {
    id: "5",
    name: "Lab Results Notification",
    description: "Alert sent when lab results are ready for review by the patient through the portal.",
    category: "Patient",
    channels: ["Push", "Email"],
    variables: ["{patient_name}", "{test_name}", "{portal_link}"],
    color: "text-[#16A34A]",
    bgColor: "bg-[#F0FDF4]",
  },
  {
    id: "6",
    name: "Prescription Ready",
    description: "Notification when a prescription has been prepared and is available for pickup or delivery.",
    category: "Patient",
    channels: ["SMS"],
    variables: ["{patient_name}", "{medication}", "{pharmacy}"],
    color: "text-[#7C3AED]",
    bgColor: "bg-[#FAF5FF]",
  },
  {
    id: "7",
    name: "Telehealth Link",
    description: "Sends the virtual meeting link to patient before their telehealth consultation begins.",
    category: "Appointment",
    channels: ["Email", "SMS"],
    variables: ["{patient_name}", "{doctor_name}", "{meeting_link}", "{time}"],
    color: "text-[#0284C7]",
    bgColor: "bg-[#EFF6FF]",
  },
  {
    id: "8",
    name: "Payment Receipt",
    description: "Digital receipt sent after a successful payment or billing transaction is processed.",
    category: "Billing",
    channels: ["Email"],
    variables: ["{patient_name}", "{amount}", "{invoice_id}", "{date}"],
    color: "text-[#16A34A]",
    bgColor: "bg-[#F0FDF4]",
  },
  {
    id: "9",
    name: "Missed Appointment",
    description: "Follow-up notification sent to patients who missed their scheduled appointment.",
    category: "Appointment",
    channels: ["SMS", "Email"],
    variables: ["{patient_name}", "{date}", "{reschedule_link}"],
    color: "text-[#EF4444]",
    bgColor: "bg-[#FEF2F2]",
  },
];
